AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - spec/dummy/db/**/*
    - vendor/bundle/**/*
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/timescaledb-rails.rb

RSpec/NestedGroups:
  Max: 4

require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
