version: '3'
services:
  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: timescaledb-rails_test
      POSTGRES_PASSWORD: postgres
