name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      db:
        image: timescale/timescaledb:latest-pg14
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: timescaledb-rails_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
        rails:
          - '6.0'
          - '7.0'
        exclude:
          - ruby: '2.6'
            rails: '7.0'

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
      RAILS_ENV: test

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Run bundle install
        run: bundle install

      - name: Run db migrate
        run: |
          export BUNDLE_GEMFILE=../../${BUNDLE_GEMFILE}
          cd spec/dummy
          bundle exec rake db:migrate
          cd ../..

      - name: Run test suite
        run: bundle exec rspec

      - name: Run rubocop
        run: bundle exec rubocop
